# Generated by Django 2.0 on 2018-01-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=256)),
                ('middleName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dlNum', models.IntegerField()),
                ('expDate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('odometer', models.IntegerField()),
                ('lpNum', models.IntegerField()),
                ('vin', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titlestor.Clients')),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titlestor.Vehicles'),
        ),
    ]
