# Generated by Django 2.0 on 2018-01-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titlestor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='client',
        ),
        migrations.AlterField(
            model_name='clients',
            name='firstName',
            field=models.CharField(default='First', max_length=256),
        ),
        migrations.AlterField(
            model_name='clients',
            name='lastName',
            field=models.CharField(default='Last', max_length=256),
        ),
        migrations.AlterField(
            model_name='clients',
            name='middleName',
            field=models.CharField(default='Middle', max_length=256),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='color',
            field=models.CharField(default='Color', max_length=256),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='make',
            field=models.CharField(default='Make', max_length=256),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='model',
            field=models.CharField(default='Model', max_length=256),
        ),
    ]
