# Generated by Django 2.0 on 2018-01-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titlestor', '0002_auto_20180104_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='First', max_length=256)),
                ('middleName', models.CharField(default='Middle', max_length=256)),
                ('lastName', models.CharField(default='Last', max_length=256)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('dlNum', models.CharField(max_length=16)),
                ('expDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(default='Make', max_length=256)),
                ('model', models.CharField(default='Model', max_length=256)),
                ('color', models.CharField(default='Color', max_length=256)),
                ('odometer', models.CharField(max_length=6)),
                ('lpNum', models.CharField(max_length=7)),
                ('vin', models.CharField(max_length=17)),
            ],
        ),
        migrations.RemoveField(
            model_name='clients',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
        migrations.AddField(
            model_name='client',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titlestor.Vehicle'),
        ),
    ]
